import PDFDocument from 'pdfkit';

/**
 * Render a personalized practice worksheet to a PDF buffer.
 */
export const renderWorksheetPdf = ({
  studentName,
  concept,
  questions = [],
  misconceptions = [],
}) => new Promise((resolve, reject) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const chunks = [];

  doc.on('data', (chunk) => chunks.push(chunk));
  doc.on('end', () => resolve(Buffer.concat(chunks)));
  doc.on('error', reject);

  doc.fontSize(20).fillColor('#1e3a5f').text('Shiksha Setu', { align: 'center' });
  doc.fontSize(14).fillColor('#334155').text('Personalized Adaptive Practice Worksheet', { align: 'center' });
  doc.moveDown(1.5);

  doc.fontSize(11).fillColor('#0f172a');
  doc.text(`Student: ${studentName}`);
  doc.text(`Focus concept: ${concept}`);
  doc.text(`Date: ${new Date().toLocaleDateString()}`);
  doc.moveDown();

  if (misconceptions.length > 0) {
    doc.fontSize(10).fillColor('#b45309').text('Targeting your Error DNA:');
    misconceptions.slice(0, 3).forEach((m) => {
      doc.fillColor('#78350f').text(`  • ${m.misconception} (${m.concept})`);
    });
    doc.moveDown();
  }

  doc.fontSize(12).fillColor('#1e3a5f').text('Practice Problems', { underline: true });
  doc.moveDown(0.5);

  questions.forEach((q, i) => {
    doc.fontSize(11).fillColor('#0f172a').text(`${i + 1}. ${q.prompt}`, {
      width: 500,
      lineGap: 4,
    });
    if (q.targetsMisconception) {
      doc.fontSize(8).fillColor('#64748b').text(`   (targets: ${q.targetsMisconception})`);
    }
    doc.moveDown(1.2);
  });

  doc.addPage();
  doc.fontSize(14).fillColor('#1e3a5f').text('Answer Key (Teacher Only)', { underline: true });
  doc.moveDown();

  questions.forEach((q, i) => {
    doc.fontSize(10).fillColor('#0f172a').text(`${i + 1}. ${q.answer}`);
    doc.moveDown(0.4);
  });

  doc.moveDown(2);
  doc.fontSize(8).fillColor('#94a3b8').text(
    'Generated by Shiksha Setu adaptive practice engine — personalized from student Error DNA.',
    { align: 'center' }
  );

  doc.end();
});
